# Exported from Render on 2024-05-08T00:59:44Z
services:
- type: web
  name: hardstop
  runtime: node
  repo: https://github.com/frevisto/hardstop
  plan: free
  region: oregon
  buildCommand: yarn
  startCommand: yarn start
  envVars:
      - key: localhost:5432 # Sets DATABASE_URL to the connection string of the hadstop database
        fromDatabase:
          name: hardstop
          property: postgreSQL
databases:
  - name: hardstop # A PostgreSQL database running on a free instance
    plan: free
version: "1"
